[package]
name = "ssl-checker"
version = "0.1.0"
edition = "2021"
authors = [""]
description = "高性能なSSL証明書チェックツール"
license = "MIT OR Apache-2.0"

[dependencies]
openssl = "0.10"
clap = { version = "4.5", features = ["derive"] }
